name: Rust

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.81"
  LLVM_VERSION: "15.0.6"

jobs:
  windows:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    # Temporarily disable this action due to additional test is needed.
    # if: false
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-pc-windows-msvc, os: windows-2022, arch: x86_64 }
          - { target: i686-pc-windows-msvc, os: windows-2022, arch: x86 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install LLVM and Clang
        uses: rustdesk-org/install-llvm-action-32bit@master
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - name: Build
        run: |
          cargo build --target ${{ matrix.job.target }}
          mkdir -p ./simple_test-debug-win-${{ matrix.job.arch }}
          mv ./target/${{ matrix.job.target }}/debug/simple_test.exe ./simple_test-debug-win-${{ matrix.job.arch }}
          mv ./target/${{ matrix.job.target }}/debug/simple_test.pdb ./simple_test-debug-win-${{ matrix.job.arch }}
          Compress-Archive -Path ./simple_test-debug-win-${{ matrix.job.arch }} -DestinationPath simple_test-debug-win-${{ matrix.job.arch }}.zip
          sha256sum simple_test-debug-win-${{ matrix.job.arch }}.zip > simple_test-debug-win-${{ matrix.job.arch }}.sha256

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: test ci
          tag_name: build_ci
          files: |
            ./simple_test-debug-win-${{ matrix.job.arch }}.zip
            ./simple_test-debug-win-${{ matrix.job.arch }}.sha256

  linux:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    # Temporarily disable this action due to additional test is needed.
    # if: false
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, arch: x86_64 }
          # - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, arch: aarch64 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install LLVM and Clang
        uses: rustdesk-org/install-llvm-action-32bit@master
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - name: Setup libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y librust-alsa-sys-dev

      - name: Build
        run: |
          cargo build --target ${{ matrix.job.target }}
          mv ./target/${{ matrix.job.target }}/debug/simple_test ./simple_test-debug-linux-${{ matrix.job.arch }}
          sha256sum ./simple_test-debug-linux-${{ matrix.job.arch }} > simple_test-debug-linux-${{ matrix.job.arch }}.sha256

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: test ci
          tag_name: build_ci
          files: |
            ./simple_test-debug-linux-${{ matrix.job.arch }}
            ./simple_test-debug-linux-${{ matrix.job.arch }}.sha256
